# Generated by Django 5.0.1 on 2024-01-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('mealname', models.CharField(blank=True, db_column='mealName', max_length=60, null=True)),
                ('menumealname', models.CharField(blank=True, db_column='menuMealName', max_length=600, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carbohydrate', models.FloatField(blank=True, null=True)),
                ('dietaryfiber', models.FloatField(blank=True, db_column='dietaryFiber', null=True)),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('salt', models.FloatField(blank=True, null=True)),
                ('saturatedfattyacids', models.FloatField(blank=True, db_column='saturatedFattyAcids', null=True)),
                ('ingredients', models.CharField(blank=True, max_length=6000, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meals',
                'managed': False,
            },
        ),
    ]
